services:
  postgres:
    image: postgres:16-alpine
    container_name: cloud_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cloud
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d cloud" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: cloud_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cloud
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./upload:/app/upload

volumes:
  postgres_data: